# Generated by Django 5.0.7 on 2024-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_catalog_attributes_ids_catalog_products_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributename',
            name='zobrazit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='published_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='kod',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='nazev',
            field=models.TextField(blank=True),
        ),
    ]
