# Generated by Django 5.0.7 on 2024-07-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_attributename_zobrazit_product_published_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='nazev',
            field=models.CharField(max_length=120),
        ),
    ]
