# Generated by Django 5.0.7 on 2024-07-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description_alter_product_nazev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cena',
            field=models.FloatField(),
        ),
    ]
