# Generated by Django 5.0.7 on 2024-07-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mena',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='nazev',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
