# Generated by Django 5.0.7 on 2024-07-29 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='attributes_ids',
            field=models.ManyToManyField(blank=True, to='products.attribute'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='nazev',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='obrazek_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.image'),
        ),
    ]
