# Generated by Django 5.0.7 on 2024-07-29 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_catalog_attributes_ids_alter_catalog_nazev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='obrazek_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.image'),
        ),
    ]
