# Generated by Django 5.0.7 on 2024-07-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_catalog_obrazek_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
